name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: netresearch/.github/.github/workflows/golib-create-release.yml@4f6d149347c61a27ce243f5ac8011d6748487341 # main
    permissions:
      contents: write
      id-token: write
      attestations: write
